demo_ltweb1/mview/mv/urls.py
from django.urls import path
from . import views

app_name = 'mv'
urlpatterns = [
    path('', views.home, name='home'),
    path('base/', views.base, name='base'),
    path('mv/', views.listMv, name='list-mv'),
    path('detail-mv/', views.detailMV, name='detail-mv'),
]

demo_ltweb1/mview/mview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mv.urls')),
    path('', include('user.urls')),
    path('accounts/', include('allauth.urls')),
]

demo_ltweb1/mview/user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

app_name = 'user'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),
    path('logout/', auth_views.LogoutView.as_view(template_name='mv/home.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', PasswordResetView.as_view(success_url=reverse_lazy('password-reset-done')), name='password-reset'),
    path('reset-password-done/', PasswordResetDoneView.as_view(),name='password-reset-done'),
    path('reset-password-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),  name='password_reset_confirm' ),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

demo_ltweb1/mview/user/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.

Sex_choice = (
    ('Nam', 'Nam'),
    ('Nữ', 'Nữ'),
    ('Không xác định', 'Không xác định'),
)


class ProfileUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='profiles_pic', blank=True)
    sex = models.CharField(choices=Sex_choice, blank=True, max_length=20)
    birthday = models.DateField()

    def __str__(self):
        return {self.user.username}

demo_ltweb1/mview/user/forms.py
import re
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UsernameField
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
    username = UsernameField(
        label="Tên đăng nhập",
        min_length=4,
        max_length=10,
        widget=forms.TextInput(attrs={'id': 'username', 'placeholder': 'Tên đăng nhập', 'class': 'username'})
    )
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(attrs={'id': 'email', 'class': 'email', 'placeholder': 'Email'})
    )
    password1 = forms.CharField(
        label="Mật khẩu",
        min_length=8,
        widget=forms.PasswordInput(attrs={'id': 'password1', 'class': 'password1', 'placeholder': 'Mật khẩu'})
    )
    password2 = forms.CharField(
        label="Nhập lại mật khẩu",
        min_length=8,
        widget=forms.PasswordInput(attrs={'id': 'password2', 'class': 'password2', 'placeholder': 'Nhập lại mật khẩu'})
    )

    error_messages = {
        'password_mismatch': 'Mật khẩu không hợp lệ',
        'username already exists': 'Tài khoản đã tồn tại',
        'Email already exists': 'Email đã tồn tại',
        "Username don't correct": 'Tên đăng nhập chứa kí tự không hợp lệ',
        'Tài khoản không tồn tại': 'Tài khoản không tồn tại',
    }

    def clean_username(self):
        username = self.cleaned_data['username']
        if re.search(r'\W+$', username):
            raise forms.ValidationError(
                self.error_messages["Username don't correct"]
            )
        r = User.objects.filter(username=username)
        if r.count():
            raise forms.ValidationError(
                self.error_messages['username already exists'])
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise forms.ValidationError(
                self.error_messages['Email already exists'])
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch']
            )
        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user


class LoginForm(forms.Form):
    username = UsernameField(
        label="Tên đăng nhập",
        min_length=4,
        max_length=10,
        widget=forms.TextInput(attrs={'id': 'username', 'class': 'username', 'placeholder': 'Tên đăng nhập'})
    )
    password = forms.CharField(
        label="Mật khẩu",
        min_length=8,
        widget=forms.PasswordInput(attrs={'id': 'password', 'class': 'password', 'placeholder': 'Mật khẩu'})
    )

    error_messages = {
        "Username don't correct": 'Tên đăng nhập và mật khẩu không phù hợp',
    }

    def clean_username(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data.get('password')
        if re.search(r'\W+$', username):
            raise forms.ValidationError(
                self.error_messages["Username don't correct"]
            )
        return username

    # def clean_username(self):
    #     username = self.cleaned_data['username']
    #     if len(username) < 4 or len(username) > 10:
    #         raise forms.ValidationError(
    #             self.error_messages["Account isn't exists1"]
    #         )
    #     if re.search(r'\W+$', username):
    #         raise forms.ValidationError(
    #             self.error_messages["Account isn't exists2"])
    # return username
    # r = User.objects.filter(email=email)
    # if re.search(r'\W+$', username):
    #     raise forms.ValidationError(
    #         self.error_messages['Email already exists'])
    # return username
    # username = self.cleaned_data['username']
    # if re.search(r'\W+$', username):
    #     raise forms.ValidationError(
    #         self.error_messages["Username don't correct"]
    #     )
    # return username
    # else:
    #     r=User.objects.filter(username=username)
    #     if not r.count():
    #         raise forms.ValidationError(
    #             self.error_messages["username don't correct"]
    #         )
    #     else:
    #         password=self.cleaned_data['password']
    #
    #         if r.password==password:

demo_ltweb1/mview/mv/views.py
from django.shortcuts import render


# Create your views here.

def home(request):
    return render(request, 'mv/home.html')


def base(request):
    return render(request, 'mv/base.html')

def listMv(request):
    return render(request, 'mv/list-mv.html')

def detailMV(request):
    return render(request, 'mv/detail-mv.html')

demo_ltweb1/mview/user/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from .forms import LoginForm, RegisterForm
from django.contrib.auth.decorators import login_required


# Create your views here.


class Login(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'user/login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            my_user = authenticate(username=username, password=password)
            if my_user is not None:
                login(request, my_user)
                return HttpResponseRedirect(reverse('mv:home'))
        return render(request, 'user/login.html', {'form': form})


class Register(View):

    def get(self, request):
        form = RegisterForm()
        return render(request, 'user/register.html', {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:login'))
        return render(request, 'user/register.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'user/profile.html')

demo_ltweb1/mview/mv/templates/mv/base.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

<!doctype html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'mv/base.css' %}">
    {% block css %}{% endblock %}
</head>

<body>

<header>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top  scrolled">


            <a class="navbar-brand" href="{% url 'mv:home' %}">Mview</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mv:home' %}">trang chủ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mv:list-mv' %}">review mv</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#famous">người nổi tiếng</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#footer">about</a>
                    </li>


                </ul>
                {% if user.is_authenticated %}
                {% if user.last_name %}
                <a href="" class="nav-item user ">{{ user.last_name }} {{ user.first_name }}</a>
                {% else %}
                <a href="" class="nav-item user ">{{ user.username }}</a>
                {% endif %}
                <div class="profile-logout text-center">
                    <div class="up"><i class="fas fa-caret-up"></i></div>
                    <div class="div-profile">
                        <ul class="m-0">
                            <li class="li-profile"><a href="">profile</a></li>
                            <li class="li-logout"><a href="{% url 'user:logout' %}">logout</a></li>
                        </ul>
                    </div>
                </div>

                {% else %}
                <button class=" nav-item btn-login btn btn-outline-success my-2 my-sm-0 " type="button">
                    <a href="{% url 'user:login' %}">Đăng nhập</a>
                </button>
                {% endif %}
            </div>
        </nav>
    </div>
</header>

{% block content %}
{% endblock %}

<footer id="footer">
    <section class="container mt-5">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <div class="content-footer">
                    <div class="text-header">
                        <h4>Liên hệ</h4>
                    </div>
                    <ul class="icon">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    </ul>
                    <ul class="infor">
                        <li><i class="fas fa-mobile-alt"></i>0321659874</li>
                        <li><i class="fas fa-envelope"></i>123456@gmail.com</li>
                    </ul>
                    <div class="copyright"><i class="fas fa-copyright"> </i>2020 NCT Corp. All rights reserved</div>
                </div>
            </div>
        </div>
    </section>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>

<!--    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"-->
<!--        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"-->
<!--        crossorigin="anonymous"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<script src="https://kit.fontawesome.com/1010e56f2f.js" crossorigin="anonymous"></script>


<script type="text/javascript">
        // <!--        script thanh dieu huong-->
        // $(document).scroll(function() {
        //     $('.navbar').toggleClass('scrolled', $(this).scrollTop() > $('.navbar').height());
        // });

        // <!--        script nut dang nhap-->
        $(document).scroll(function() {

            $('.btn-login').toggleClass('btn-login-display', $(this).scrollTop() > $('.navbar').height());
        });

        //<!--        script hover nut dang nhap-->
        $(document).ready(function() {
            $(".user").hover(function() {
                $(".profile-logout").css('display', 'inline-block');
            }, function() {
                $(".profile-logout").css('display', 'none');
            });
        });

        //<!--        script cho div-login-parent-->
        $(document).ready(function() {
            $(".profile-logout").mouseover(function() {
                $(this).css('display', 'inline-block')
            });
            $(".profile-logout").mouseout(function() {
                $(this).css('display', 'none')
            });
        });

</script>
</body>

</html>

demo_ltweb1/mview/mv/templates/mv/home.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <title>Mview</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>-->


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css"/>

    <link rel="stylesheet" href="{% static 'mv/home.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.0.js"
            integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc=" crossorigin="anonymous"></script>
</head>

<body class="body" data-spy="scroll" data-target=".navbar" data-offset="500">

<header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href=".">Mview</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#home">trang chủ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#mv">review mv</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#famous">người nổi tiếng</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#footer">about</a>
                </li>


            </ul>
            {% if user.is_authenticated %}
            {% if user.last_name %}
            <a href="" class="nav-item user ">{{ user.last_name }} {{ user.first_name }}</a>
            {% else %}
            <a href="" class="nav-item user ">{{ user.username }}</a>
            {% endif %}
            <div class="profile-logout text-center">
                <div class="up"><i class="fas fa-caret-up"></i></div>
                <div class="div-profile">
                    <ul class="m-0">
                        <li class="li-profile"><a href="">profile</a></li>
                        <li class="li-logout"><a href="{% url 'user:logout' %}">logout</a></li>
                    </ul>
                </div>


            </div>
            {% else %}
            <button class=" nav-item btn-login btn btn-outline-success my-2 my-sm-0 " type="button">
                <a href="{% url 'user:login' %}">Đăng nhập</a>
            </button>
            {% endif %}
        </div>
    </nav>

</header>

<div class="jumbotron jumbotron-fluid height100p banner" id="home">
    <div class="container h100">
        <div class="content-banner h100">
            <div>
                <h1 data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">mview</h1>
                <p data-aos="fade-up" data-aos-duration="1000" data-aos-delay="500">
                    Mview là một trang blog chuyên review mv và người nổi tiếng; nhận xét, đánh giá, tóm tắt
                    nội dung các mv trong nước và quốc tế với cảm nhận cá nhân
                </p>
            </div>
        </div>
    </div>
</div>

<section class="sec1" id="mv">
    <div class="container">
        <div class="row">
            <div class="offset-sm-2 col-sm-8">
                <div class="headerText text-center">
                    <br>
                    <br>
                    <h2 data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">Music Video</h2>
                    <p data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">là các clip âm nhạc, video âm
                        nhạc, video ca nhạc. Đây là một dạng phim ngắn kết hợp với âm thanh bài hát cùng hình ảnh
                        được sản xuất với mục đích nghệ thuật.</p>
                </div>
            </div>
        </div>
        <div class="row">
            {% for i in "abcdef" %}
            <div class="col-sm-4 col-xs-12">
                <div class="mvBox" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200">
                    <a href="{% url 'mv:detail-mv' %}">
                        <div class="img-mv">
                            <img class="img-fluid" src="{% static 'mv/mv.jpg' %}" alt="">
                            <div class="layer2"></div>
                            <div class="eye"><i class="far fa-eye"></i></div>
                            <div class="heart"><i class="far fa-heart"></i>
                                <p>123</p></div>
                        </div>
                    </a>
                    <div class="content-mvBox">
                        <h5><a class="title" href="{% url 'mv:detail-mv' %}">Yêu Một Người Tổn Thương Là Sẽ Như Vậy</a>
                        </h5>
                        <p>Bùi Anh Tuấn, Dương Quý Tần</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="container" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="250">
                <div class="row">
                    <div class="col-sm-10"></div>
                    <div class="col-sm-2">
                        <a href="{% url 'mv:list-mv' %}">Xem thêm ...</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="sec2" id="famous">
    <div class="container">
        <div class="row">
            <div class="offset-sm-2 col-sm-8">
                <div class="headerText text-center">
                    <h2 data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200">Người nổi tiếng</h2>
                </div>
            </div>
        </div>
        <div class="row">
            {% for i in "abcdefgh" %}
            <div class="col-sm-3 col-xs-12">
                <div class="faBox" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="250">
                    <div class="img-famous">
                        <img class="img-fluid" src="{% static 'mv/fa.jpg' %}" alt="">
                    </div>
                    <div class="content-faBox">
                        <h5>Bùi Anh Tuấn</h5>
                    </div>
                </div>
            </div>
            {% endfor %}

            <div class="container">
                <div class="row">
                    <div class="col-sm-10"></div>
                    <div class="col-sm-2" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200">
                        <a href="">Xem thêm ...</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

<footer id="footer">
    <section class="container">
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <div class="content-footer">
                    <div class="text-header">
                        <h4>Liên hệ</h4>
                    </div>
                    <ul class="icon">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    </ul>
                    <ul class="infor">
                        <li><i class="fas fa-mobile-alt"></i>0321659874</li>
                        <li><i class="fas fa-envelope"></i>123456@gmail.com</li>
                    </ul>
                    <div class="copyright"><i class="fas fa-copyright"> </i>2020 NCT Corp. All rights reserved</div>
                </div>
            </div>
        </div>
    </section>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>

<!--    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"-->
<!--        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"-->
<!--        crossorigin="anonymous"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<script src="https://kit.fontawesome.com/1010e56f2f.js" crossorigin="anonymous"></script>

<script type="text/javascript">
<!--        script thanh dieu huong-->
        $(document).scroll(function () {
            $('.navbar').toggleClass('scrolled', $(this).scrollTop() > $('.navbar').height());
        });

<!--        script nut dang nhap-->
         $(document).scroll(function () {

            $('.btn-login').toggleClass('btn-login-display', $(this).scrollTop() > $('.navbar').height());
        });

<!--        script hover nut dang nhap-->
        $(document).ready(function(){
            $(".user").hover(function(){
                $(".profile-logout").css('display', 'inline-block');
            }, function(){
                $(".profile-logout").css('display', 'none');
            });
        });

<!--        script cho div-login-parent-->
        $(document).ready(function(){
            $(".profile-logout").mouseover(function(){
                $(this).css('display', 'inline-block')
            });
            $(".profile-logout").mouseout(function(){
                $(this).css('display', 'none')
            });
        });





</script>
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
        AOS.init();
</script>

</body>
</html>

demo_ltweb1/mview/user/templates/user/login.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'user/login.css' %}">
</head>
<body>
<form action="" method="post" class="Form">
    {% csrf_token %}
    <h1>ĐĂNG NHẬP</h1>
    {{ form.as_p }}

    <p><input type="submit" value="Đăng nhập"></p>
    <ul class="auth text-center" >
        <li><a href="{% url 'user:register' %}">Tạo tài khoản</a></li>
        <li><a href="{% provider_login_url 'facebook' method='oauth2'%}">Đăng nhập bằng facebook</a></li>
        <li><a href="{% provider_login_url 'google'%}">Đăng nhập bằng google</a></li>
    </ul>
</form>

</body>
</html>

demo_ltweb1/mview/user/templates/user/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Đăng xuất</title>
</head>
<body>
<a href=""> login again </a>
</body>
</html>

demo_ltweb1/mview/user/templates/user/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

demo_ltweb1/mview/user/templates/user/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Register</title>
        <link rel="stylesheet" href="{% static 'user/register.css' %}" >
      </head>
    <body>
        <form action="" method="post" class="Form">
            {% csrf_token %}
            <h1>TẠO TÀI KHOẢN</h1>
            {{ form.as_p }}
            <p><input type="submit" value="Đăng kí"></p>
        </form>
    </body>
</html>